config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/FAIR_eva:
      branch: main
      repo: https://github.com/EOSC-synergy/FAIR_eva
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-ecru-guppy.sh
        container: qc.acc_flabby-indigo-meerkat
  QC.Doc:
    repos:
      github.com/EOSC-synergy/FAIR_eva find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-taupe-dugong.sh
        container: qc.doc_shabby-cerulean-fossa
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-cinnamon-burmese.sh
        container: qc.doc_nerdy-cyan-blue
      github.com/EOSC-synergy/FAIR_eva markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-azure-seal.sh
        container: qc.doc_scanty-pink-robin
      github.com/EOSC-synergy/FAIR_eva restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-denim-dolphin.sh
        container: qc.doc_tasty-cobalt-chipmunk
  QC.Lic:
    repos:
      github.com/EOSC-synergy/FAIR_eva licensee:
        commands:
        - /usr/bin/env sh .sqa/script.surly-firebrick-dodo.sh
        container: qc.lic_sloppy-aqua-terrier
  QC.Met:
    repos:
      github.com/EOSC-synergy/FAIR_eva cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-flax-chin.sh
        container: qc.met_paltry-brown-dragonfly
  QC.Sec:
    repos:
      github.com/EOSC-synergy/FAIR_eva bandit:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-copper-loon.sh
        container: qc.sec_breezy-olive-toad
  QC.Sty:
    repos:
      github.com/EOSC-synergy/FAIR_eva flake8:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-orange-quoll.sh
        container: qc.sty_hazy-black-antelope
      github.com/EOSC-synergy/FAIR_eva hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-ivory-beetle.sh
        container: qc.sty_shaggy-khaki-dhole
      github.com/EOSC-synergy/FAIR_eva jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-apricot-koala.sh
        container: qc.sty_snoopy-gold-toucan
  QC.Uni:
    repos:
      github.com/EOSC-synergy/FAIR_eva pytest:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-sepia-mastiff.sh
        container: qc.uni_foggy-saffron-setter
  QC.Ver:
    repos:
      github.com/EOSC-synergy/FAIR_eva get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-ruby-starfish.sh
        container: qc.ver_squeaky-turquoise-bandicoot
timeout: 5400
