config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/FAIR_eva:
      branch: main
      repo: https://github.com/EOSC-synergy/FAIR_eva
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-emerald-rat.sh
        container: qc.acc_crappy-chartreuse-panda
  QC.Doc:
    repos:
      github.com/EOSC-synergy/FAIR_eva find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-aqua-ray.sh
        container: qc.doc_blurry-smalt-coral
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-amber-hyena.sh
        container: qc.doc_foggy-cornflower-akita
      github.com/EOSC-synergy/FAIR_eva markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-violet-dog.sh
        container: qc.doc_goopy-periwinkle-sheep
      github.com/EOSC-synergy/FAIR_eva restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-olive-hyrax.sh
        container: qc.doc_chummy-olivine-horse
  QC.Lic:
    repos:
      github.com/EOSC-synergy/FAIR_eva licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-beige-markhor.sh
        container: qc.lic_messy-asparagus-tamarin
  QC.Met:
    repos:
      github.com/EOSC-synergy/FAIR_eva cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-gamboge-seahorse.sh
        container: qc.met_sunny-cream-panda
  QC.Sec:
    repos:
      github.com/EOSC-synergy/FAIR_eva bandit:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-wheat-gorilla.sh
        container: qc.sec_squirrely-firebrick-turtle
  QC.Sty:
    repos:
      github.com/EOSC-synergy/FAIR_eva flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-dandelion-albatross.sh
        container: qc.sty_trippy-cobalt-octopus
      github.com/EOSC-synergy/FAIR_eva hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-ochre-chinchilla.sh
        container: qc.sty_cozy-magenta-boar
      github.com/EOSC-synergy/FAIR_eva jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-beige-russel.sh
        container: qc.sty_queasy-platinum-akbash
  QC.Uni:
    repos:
      github.com/EOSC-synergy/FAIR_eva pytest:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-silver-shrew.sh
        container: qc.uni_queasy-firebrick-angora
  QC.Ver:
    repos:
      github.com/EOSC-synergy/FAIR_eva get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-russet-wrasse.sh
        container: qc.ver_geeky-yellow-wolfhound
timeout: 5400
