config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/FAIR_eva:
      branch: main
      repo: https://github.com/EOSC-synergy/FAIR_eva
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.3.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-apricot-zebra.sh
        container: qc.acc_hazy-charcoal-bison
  QC.Doc:
    repos:
      github.com/EOSC-synergy/FAIR_eva find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-cinnabar-orangutan.sh
        container: qc.doc_stealthy-magnolia-giraffe
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-bronze-setter.sh
        container: qc.doc_skanky-turquoise-discus
      github.com/EOSC-synergy/FAIR_eva markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-khaki-chameleon.sh
        container: qc.doc_chewy-pear-tarantula
      github.com/EOSC-synergy/FAIR_eva restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-saffron-frigatebird.sh
        container: qc.doc_beady-olivine-avocet
  QC.Lic:
    repos:
      github.com/EOSC-synergy/FAIR_eva licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-gold-fousek.sh
        container: qc.lic_cloudy-chartreuse-giraffe
  QC.Met:
    repos:
      github.com/EOSC-synergy/FAIR_eva cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-malachite-duck.sh
        container: qc.met_greasy-linen-wolfhound
  QC.Sec:
    repos:
      github.com/EOSC-synergy/FAIR_eva bandit:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-olive-caracal.sh
        container: qc.sec_hazy-ochre-badger
  QC.Sty:
    repos:
      github.com/EOSC-synergy/FAIR_eva flake8:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-linen-caiman.sh
        container: qc.sty_whiny-peach-bordeaux
  QC.Uni:
    repos:
      github.com/EOSC-synergy/FAIR_eva pytest:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-bistre-bonobo.sh
        container: qc.uni_sloppy-olive-zorse
  QC.Ver:
    repos:
      github.com/EOSC-synergy/FAIR_eva get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-tomato-termite.sh
        container: qc.ver_craggy-amber-newfoundland
timeout: 5400
