config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/FAIR_eva:
      branch: main
      repo: https://github.com/EOSC-synergy/FAIR_eva
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-wheat-ibis.sh
        container: qc.acc_woolly-maroon-wrasse
  QC.Doc:
    repos:
      github.com/EOSC-synergy/FAIR_eva find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-bronze-eel.sh
        container: qc.doc_trippy-dandelion-caracal
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-myrtle-barb.sh
        container: qc.doc_hilly-tomato-cow
      github.com/EOSC-synergy/FAIR_eva markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-russet-mammoth.sh
        container: qc.doc_hazy-flax-octopus
      github.com/EOSC-synergy/FAIR_eva restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-chestnut-anteater.sh
        container: qc.doc_lousy-ruby-sheep
  QC.Lic:
    repos:
      github.com/EOSC-synergy/FAIR_eva licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-coral-mole.sh
        container: qc.lic_gloppy-white-boar
  QC.Met:
    repos:
      github.com/EOSC-synergy/FAIR_eva cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-lavender-turtle.sh
        container: qc.met_stinky-celadon-booby
  QC.Sec:
    repos:
      github.com/EOSC-synergy/FAIR_eva bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-cinnabar-numbat.sh
        container: qc.sec_zippy-buff-oriole
  QC.Sty:
    repos:
      github.com/EOSC-synergy/FAIR_eva flake8:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-red-wolfhound.sh
        container: qc.sty_fuzzy-aquamarine-goose
      github.com/EOSC-synergy/FAIR_eva hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-yellow-lemming.sh
        container: qc.sty_cloudy-periwinkle-squid
      github.com/EOSC-synergy/FAIR_eva jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-rose-lobster.sh
        container: qc.sty_geeky-taupe-lemur
  QC.Uni:
    repos:
      github.com/EOSC-synergy/FAIR_eva pytest:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-khaki-indri.sh
        container: qc.uni_silly-lilac-slug
  QC.Ver:
    repos:
      github.com/EOSC-synergy/FAIR_eva get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-pear-spitz.sh
        container: qc.ver_nippy-lilac-ostrich
timeout: 5400
