config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/FAIR_eva:
      branch: main
      repo: https://github.com/EOSC-synergy/FAIR_eva
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-cinnamon-caiman.sh
        container: qc.acc_beady-purple-nightingale
  QC.Doc:
    repos:
      github.com/EOSC-synergy/FAIR_eva find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-myrtle-kangaroo.sh
        container: qc.doc_homely-green-seal
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-amber-hare.sh
        container: qc.doc_cheeky-gold-vulture
      github.com/EOSC-synergy/FAIR_eva markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-jade-mammoth.sh
        container: qc.doc_lanky-mustard-burmese
      github.com/EOSC-synergy/FAIR_eva restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-champagne-bison.sh
        container: qc.doc_beady-cream-camel
  QC.Lic:
    repos:
      github.com/EOSC-synergy/FAIR_eva licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-turquoise-elephant.sh
        container: qc.lic_bluesy-alizarin-bullfrog
  QC.Met:
    repos:
      github.com/EOSC-synergy/FAIR_eva cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-magnolia-lizard.sh
        container: qc.met_zippy-salmon-tarantula
  QC.Sec:
    repos:
      github.com/EOSC-synergy/FAIR_eva bandit:
        commands:
        - /usr/bin/env sh .sqa/script.randy-pink-worm.sh
        container: qc.sec_freaky-turquoise-caterpillar
  QC.Sty:
    repos:
      github.com/EOSC-synergy/FAIR_eva flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-khaki-binturong.sh
        container: qc.sty_woolly-harlequin-meerkat
      github.com/EOSC-synergy/FAIR_eva hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-celadon-bullfrog.sh
        container: qc.sty_muzzy-goldenrod-quetzal
  QC.Ver:
    repos:
      github.com/EOSC-synergy/FAIR_eva get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-sapphire-scorpion.sh
        container: qc.ver_randy-gamboge-rattlesnake
timeout: 5400
