config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/FAIR_eva:
      branch: main
      repo: https://github.com/EOSC-synergy/FAIR_eva
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-auburn-bee.sh
        container: qc.acc_trippy-myrtle-capuchin
  QC.Doc:
    repos:
      github.com/EOSC-synergy/FAIR_eva find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-bronze-grouse.sh
        container: qc.doc_flabby-cyan-cougar
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-lime-mayfly.sh
        container: qc.doc_cloudy-silver-uakari
      github.com/EOSC-synergy/FAIR_eva markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-cinnamon-reindeer.sh
        container: qc.doc_scaly-teal-meerkat
      github.com/EOSC-synergy/FAIR_eva restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-gold-scorpion.sh
        container: qc.doc_greasy-zucchini-camel
  QC.Lic:
    repos:
      github.com/EOSC-synergy/FAIR_eva licensee:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-eggplant-abyssinian.sh
        container: qc.lic_craggy-russet-ostrich
  QC.Met:
    repos:
      github.com/EOSC-synergy/FAIR_eva cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-linen-neanderthal.sh
        container: qc.met_scummy-chartreuse-alligator
  QC.Sec:
    repos:
      github.com/EOSC-synergy/FAIR_eva bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-orchid-moorhen.sh
        container: qc.sec_paltry-cream-bee
  QC.Sty:
    repos:
      github.com/EOSC-synergy/FAIR_eva flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-corn-bulldog.sh
        container: qc.sty_nippy-peach-schnauzer
      github.com/EOSC-synergy/FAIR_eva hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-burgundy-drever.sh
        container: qc.sty_thirsty-chestnut-hummingbird
      github.com/EOSC-synergy/FAIR_eva jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-asparagus-snake.sh
        container: qc.sty_grumpy-brass-jackal
  QC.Uni:
    repos:
      github.com/EOSC-synergy/FAIR_eva pytest:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-brass-whale.sh
        container: qc.uni_sunny-heliotrope-kakapo
  QC.Ver:
    repos:
      github.com/EOSC-synergy/FAIR_eva get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-rose-okapi.sh
        container: qc.ver_shaky-grey-abyssinian
timeout: 5400
