config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/FAIR_eva:
      branch: main
      repo: https://github.com/EOSC-synergy/FAIR_eva
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.3.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-lemon-ostrich.sh
        container: qc.acc_silly-malachite-warthog
  QC.Doc:
    repos:
      github.com/EOSC-synergy/FAIR_eva find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-gamboge-cassowary.sh
        container: qc.doc_surly-coral-newt
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-dandelion-wolf.sh
        container: qc.doc_gummy-gamboge-cuttlefish
      github.com/EOSC-synergy/FAIR_eva markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-salmon-cat.sh
        container: qc.doc_breezy-cobalt-lizard
      github.com/EOSC-synergy/FAIR_eva restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-firebrick-lizard.sh
        container: qc.doc_flimsy-lavender-paradise
  QC.Lic:
    repos:
      github.com/EOSC-synergy/FAIR_eva licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-brown-bird.sh
        container: qc.lic_woozy-azure-gecko
  QC.Met:
    repos:
      github.com/EOSC-synergy/FAIR_eva cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-cobalt-foxhound.sh
        container: qc.met_flabby-bistre-barnacle
  QC.Sec:
    repos:
      github.com/EOSC-synergy/FAIR_eva bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-tangerine-walrus.sh
        container: qc.sec_messy-cornflower-fossa
  QC.Sty:
    repos:
      github.com/EOSC-synergy/FAIR_eva flake8:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-taupe-serval.sh
        container: qc.sty_craggy-magenta-emu
  QC.Uni:
    repos:
      github.com/EOSC-synergy/FAIR_eva pytest:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-burgundy-oriole.sh
        container: qc.uni_scanty-rust-robin
  QC.Ver:
    repos:
      github.com/EOSC-synergy/FAIR_eva get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-chestnut-fish.sh
        container: qc.ver_gummy-salmon-warthog
timeout: 5400
