config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/FAIR_eva:
      branch: main
      repo: https://github.com/EOSC-synergy/FAIR_eva
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Sty:
    repos:
      github.com/EOSC-synergy/FAIR_eva PyOphidia:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-thistle-peccary.sh
        container: qc.sty_wimpy-cardinal-labradoodle
timeout: 5400
