config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/FAIR_eva:
      branch: main
      repo: https://github.com/EOSC-synergy/FAIR_eva
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.3.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-asparagus-dragon.sh
        container: qc.acc_surly-vermilion-goose
  QC.Doc:
    repos:
      github.com/EOSC-synergy/FAIR_eva find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-charcoal-badger.sh
        container: qc.doc_pasty-puce-schnauzer
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-asparagus-wolverine.sh
        container: qc.doc_muggy-heliotrope-birman
      github.com/EOSC-synergy/FAIR_eva markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-red-reindeer.sh
        container: qc.doc_pokey-puce-frigatebird
      github.com/EOSC-synergy/FAIR_eva restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-plum-bonobo.sh
        container: qc.doc_snoopy-lavender-jellyfish
  QC.Lic:
    repos:
      github.com/EOSC-synergy/FAIR_eva licensee:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-champagne-gecko.sh
        container: qc.lic_pretty-firebrick-horse
  QC.Met:
    repos:
      github.com/EOSC-synergy/FAIR_eva cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-zucchini-saola.sh
        container: qc.met_bumpy-sapphire-squirrel
  QC.Sec:
    repos:
      github.com/EOSC-synergy/FAIR_eva bandit:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-coral-bobcat.sh
        container: qc.sec_flaky-seashell-frog
  QC.Sty:
    repos:
      github.com/EOSC-synergy/FAIR_eva flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-carmine-mist.sh
        container: qc.sty_skanky-ecru-gibbon
  QC.Uni:
    repos:
      github.com/EOSC-synergy/FAIR_eva pytest:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-puce-uguisu.sh
        container: qc.uni_woozy-cinnamon-rottweiler
  QC.Ver:
    repos:
      github.com/EOSC-synergy/FAIR_eva get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-zucchini-jellyfish.sh
        container: qc.ver_crabby-cinnabar-bird
timeout: 5400
